### ISSUE TITLE
完成基本样式

### ISSUE THREAD

**Issue by violet-day** [biubiubiuuuuu/biubiubiu#1]
- [x] 自定义字体
- [x] 自定义弹幕类型
- [x] 切换是否显示弹幕
- [x] 字体颜色
- [x] 包装成组件

样式参考：http://www.bilibili.com/

**Comment by facesea** [comment]
@violet-day  已完成，提交pr。
需要你重新嵌一下提交服务器的代码，可搜索TODO。
